version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    command: npm start
    ports:
      - "3000:3000"
    volumes: 
      - ".:/app"
      - "/tmp:/tmp"
    depends_on:
      - database

  database:
    image: postgres:latest
    env_file: .env         
    volumes: 
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: